//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHW_Teachers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Homework()
        {
            this.HomeworksComments = new HashSet<HomeworksComment>();
            this.HomeworksFans = new HashSet<HomeworksFan>();
            this.StudentsHomeworks = new HashSet<StudentsHomework>();
        }
    
        public int id { get; set; }
        public int taskId { get; set; }
        public int groupId { get; set; }
        public byte[] submittedFile { get; set; }
        public System.DateTime dateSubmitted { get; set; }
        public string grade { get; set; }
        public string review { get; set; }
        public int likesCount { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeworksComment> HomeworksComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeworksFan> HomeworksFans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsHomework> StudentsHomeworks { get; set; }
    }
}
